"""Revise the audited manuscript with strict source-only structure; no model calls."""
from pathlib import Path
import copy
import csv
import json
import re

from build_revision_content import revise_blocks

OUT = Path(__file__).resolve().parent
old = json.loads((OUT / 'evidence/previous_draft/manuscript_content.json').read_text())
B = copy.deepcopy(old['blocks'])

def p(text): return {'type': 'paragraph', 'text': text}
def h(text, level=2): return {'type': 'heading', 'level': level, 'text': text}
def table(label, headers, rows, note):
    return {'type': 'table', 'label': label, 'headers': headers, 'rows': rows, 'note': note}
def fig(name, label, caption): return {'type': 'figure', 'name': name, 'label': label, 'caption': caption}

TITLE = 'Source-only model selection and limits of shared spectral representations in cross-subject motor-imagery EEG decoding'
SUBTITLE = 'Strict zero-calibration evaluation with separate external cohorts and BNCI sensor-level physiology'

B[1] = p('Objective. We examined how training-duration selection and fixed spectral parameter sharing affect cross-subject motor-imagery EEG decoding without target fitting. Methods. An exploratory four-class study used nine BNCI2014_001 participants, holding out both sessions of each target person. Archived predictions were re-audited alongside source partitions, duration schedules, matched-runtime controls, and robustness interventions. Separate binary source models were evaluated on PhysioNet (109 people), Cho2017 (52 people), and the offline-training runs of Lee2019 (54 people, two sessions). Cohorts and protocols were analyzed separately. Results. Mean-rank rather than mean-loss duration selection increased internal balanced accuracy from 33.72% to 42.67%; two people accounted for 87.57% of the aggregate gain. A matched-runtime fixed-duration comparison had a positive mean but improved only four of nine people. Shared mu/beta EEGNet did not improve internal performance. Its external shared-minus-broad differences were +0.573 percentage points (pp) on PhysioNet (95% bootstrap interval [−0.097, 1.242]), −1.513 pp on Cho2017 [−2.249, −0.804], and +0.204 pp on Lee2019 [−0.515, 0.969]. The two-cohort Holm-adjusted permutation p-values for Cho2017 and Lee2019 were 0.000100 and 0.604. The latter evaluations used 15 source fits and no target fits; their final raw-to-prediction scientific validation and publication readback passed. Conclusion. Training-duration decisions can produce large, concentrated changes in a small development benchmark. Fixed spectral sharing offered no consistent transfer advantage and reduced performance on Cho2017. These results support participant-level selection diagnostics and explicit protocol auditing. Unknown native voltage calibration and acquisition-reference details constrain physiological and deployment interpretations.')
B[2] = p('Keywords: motor imagery; EEG; cross-subject decoding; EEGNet; source-only model selection; spectral parameter sharing; external evaluation; reproducibility.')

# Retain the audited implementation description; revise the framing around all completed cohorts.
B[4] = p('Motor-imagery EEG decoding must distinguish imagined actions in scalp recordings whose spatial and spectral structure varies between people. A calibration-free model should transfer to a new person without fitting to that person’s labels or distributional statistics. This differs from within-person evaluation and from adaptation using unlabeled target recordings. BCI Competition IV dataset 2a provides a small, well-documented benchmark [1,2], but its nine participants make a mean especially sensitive to a few large changes. Broader reviews and multi-dataset evaluation frameworks emphasize both variation between datasets and the dependence of reported performance on evaluation design [16,17].')
B[7] = p('We separate three questions that are often merged in decoder comparisons. First, can heterogeneous source-validation loss curves lead to very short training schedules, and does within-fold rank aggregation change those schedules? Second, does processing predefined mu/beta views with one shared EEGNet improve on a broad input when spatial, capacity, and robustness controls are reported? Third, how does that representation behave in external binary transfer? The external evidence comprises an earlier PhysioNet evaluation [9,10] and a subsequently frozen, separately fitted pipeline for Cho2017 [12,13] and Lee2019 [14,15]. These are separate evaluations with different channel sets and time windows, not a pooled benchmark score.')
B[8] = p('This study contributes an experimental audit of model selection and transfer limits. It retains negative and adverse conditions, uses the person as the inference unit, and identifies which comparisons are exploratory, runtime-matched, or externally frozen. The design follows the broader observation that model selection belongs inside a domain-generalization evaluation, rather than outside its account of the method [18]. The manuscript was prepared from completed experiments and independent reanalysis of saved predictions; no EEG model was fitted or used for fresh inference during manuscript preparation.')
physionet_population = copy.deepcopy(B[12])
B[12] = p('Cho2017 [12,13] supplies left/right-hand imagery recordings from 52 people at a native 512 Hz. The audited evaluation retains 10,520 imagery trials: 49 people have 200 trials and three (S7, S9, S46) have 240. The Lee2019 motor-imagery data [14,15] contain 54 people recorded at 1,000 Hz in two sessions. We retain only EEG_MI_train, the provider’s offline-training runs, giving 100 trials per session and 10,800 trials in total. EEG_MI_test, other paradigms, and non-imagery events are outside this evaluation. The provider’s term “train” describes a recording segment: these external trials were used for inference and scoring, never for parameter fitting. We do not assert that the three external cohorts represent 215 independently verified unique identities across providers.')
B[13] = table('Table 1. Distinct populations and computational endpoints.', ['Analysis', 'People', 'Classes', 'Unique trials', 'Primary tensor'], [
    ['Internal BNCI', '9', '4', '5,184', '22 × 750 at 250 Hz'],
    ['Q14 binary BNCI source', '9', '2', '2,592', '22 × 480 at 160 Hz'],
    ['Q14 external PhysioNet', '109', '2', '4,918', '22 × 480 at 160 Hz'],
    ['Q15 binary BNCI source', '9', '2', '2,592', '21 × 320 at 160 Hz'],
    ['Q15 external Cho2017', '52', '2', '10,520', '21 × 320 at 160 Hz'],
    ['Q15 external Lee2019', '54', '2', '10,800', '21 × 320 at 160 Hz'],
], 'Each BNCI outer target has both sessions held out. Q14 and Q15 use separate binary source fits and preprocessing contracts. Neural inputs contain EEG channels only. Prediction-table rows repeat trials across models/seeds and are not independent participants; Lee sessions are pooled within person for the primary endpoint.')
B[31] = h('2.6. Earlier binary source freeze and PhysioNet evaluation')
B[35] = h('2.8. Endpoints, uncertainty, and evidence verification')
B[37] = p(B[37]['text'] + ' For Lee2019, the two retained sessions are pooled before calculating each person/seed balanced accuracy. We then average the three neural-seed scores within person; this is an average of scores, not an ensemble of probabilities. A single CSP score is retained per person. Cross-cohort differences in scores are descriptive because Q14 and Q15 differ in source preprocessing and checkpoints.')
B[38] = p(B[38]['text'].replace('The external primary contrast', 'The earlier PhysioNet primary contrast') + ' For Q15, the predeclared family contains exactly two shared-minus-broad contrasts, one for each external cohort. Percentile person-bootstrap intervals use 20,000 draws with seed 20260924 [20]. Two-sided person-level sign-flip tests use 20,000 Monte Carlo draws with seed 20261003, assuming sign exchangeability of paired person effects under the null, evaluating the absolute mean, and applying the (exceedances + 1)/(20,000 + 1) correction [21]. Holm adjustment controls this two-contrast family [19]; it does not retroactively incorporate the earlier PhysioNet or internal hypotheses. The smallest attainable Monte Carlo p-value is 1/20,001. The intervals are unadjusted 95% intervals, and CSP comparisons are descriptive context. Descriptive Q15 counts of positive, negative, and tied person effects use an absolute 10^−15 tolerance for ties; the frozen primary bootstrap and sign-flip calculations retain the saved numerical effects.')
B[40] = p('The manuscript audit independently reaggregated 809,434 saved prediction rows across 38 earlier arms and 149,240 Q15 rows. Trial keys were checked for duplication and matched to the relevant scoring population. Q15 saved labels and event sample identities were also matched to canonical metadata in the audited raw receipts; subject confusion matrices, seed-averaged scores, bootstrap intervals, sign-flip p-values, and Holm adjustment were reproduced. This manuscript reanalysis did not load raw EEG or deserialize checkpoints. It is distinct from the completed cloud validator’s raw-to-prediction replay. For the earlier experiments, validation depth remains experiment-specific: the early spectral batch has orchestration-only top-level validation, and the final Q14 portability audit rechecks saved probabilities rather than generating fresh predictions. Text artifacts with documented CRLF-to-LF conversion are identified explicitly instead of being described as byte-identical.')
B[50] = p('In the additive matched-runtime experiment, the historical mean-loss duration schedule gave 33.92% balanced accuracy, versus 43.99% for fixed 20 epochs. The fixed-minus-historical-schedule mean was +10.06 pp, with bootstrap 95% interval [+0.68,+21.53] pp and exact sign-flip p = 0.125. Only four of nine people improved, five worsened, and the median difference was −0.174 pp. The positive mean therefore reflects large recoveries rather than a typical-person benefit. Matching runtime retains the average schedule contrast, but does not establish 20 epochs as universally preferable; historical epoch counts were reused rather than newly selected under that runtime.')
B[59] = h('3.5. Earlier PhysioNet transfer: a small, uncertain primary effect')

# Replace discussion as a coherent interpretation of the completed, adverse as well as null results.
discussion = [h('4. Discussion', 1), h('4.1. Duration selection can dominate a representation comparison'),
p('The most conspicuous internal changes arose from training duration. At two epochs, S3 remained near chance with raw or source-normalized inputs; at 16 epochs, both inputs performed substantially better. Rank aggregation subsequently changed the source-selected schedule and recovered performance for S3 and S8. The matched-runtime control retained a large mean difference between fixed training and the historical mean-loss schedule. These observations make selected duration, source-validation trajectories, per-class recall, and prediction concentration necessary diagnostic outputs when a cross-person neural model appears to collapse.'),
p('The evidence supports a diagnostic claim rather than a general prescription. Rank aggregation removes within-fold loss scale but discards magnitude information, and equal fold weighting is itself a choice. The internal candidate was developed after inspecting this benchmark. Moreover, the matched-runtime fixed-duration mean improved while the median person worsened. The external experiments did not compare rank versus mean-loss selection, so they cannot establish independent transfer of the internal rank-selection gain. A prospective comparison must freeze candidate selection rules before new-person outcomes are seen and match runtime, available source examples, and update budgets.'),
h('4.2. Spectral sharing has cohort-dependent costs'),
p('The completed external evaluations change the interpretation from an uncertain positive signal to a clear limit on generality. Shared mu/beta input gave no internal advantage, a small uncertain positive estimate on PhysioNet, a corrected negative contrast on Cho2017, and an uncertain near-zero contrast on Lee2019. The adverse Cho2017 result is evidence against a consistent advantage of this fixed representation under the evaluated source-only adapter. It does not demonstrate that mu/beta rhythms are uninformative, that all parameter sharing is harmful, or that another band definition would succeed.'),
p('Class recalls clarify what the cohort means obscure. On Cho2017, sharing reduced mean left-hand recall while increasing right-hand recall; on Lee2019, its corresponding recall changes partly offset. These are descriptive effects of the frozen model, not a post hoc label correction or a physiological mechanism. They are compatible with several unisolated causes, including differences in spatial montage, acquisition reference, exported amplitude scale, temporal alignment, and the constraints imposed by averaging band logits. No intervention in this study identifies which cause produced the adverse contrast.'),
p('Parameter economy also differs from compute economy. The shared network has one parameter set but evaluates two band views and shares their BatchNorm statistics. The independent-branch controls change capacity and normalization behavior, while the broadband capacity comparator has a small disclosed parameter mismatch. The source-fitted CSP model transfers poorly and asymmetrically in Q15. Exceeding that contextual comparator cannot be used to claim practical or clinical reliability. None of these experiments is a comparison against contemporary target-adaptation or foundation-model methods under a common budget, and no state-of-the-art claim is made.'),
h('4.3. The unit of evidence is the person'),
p('Repeated seeds reduce sensitivity to one stochastic fit but do not add participants. Lee2019 sessions and source-identity subsets are repeated measurements within a person. We consequently use person-level paired effects, retain all declared people, and show the directions of individual differences. The bootstrap intervals condition on the frozen source models; they exclude uncertainty from choosing another nine-person source cohort, another acquisition adapter, or another research-development history. Overlapping outer training sets also complicate a simple independent-person interpretation of the nine-person internal study.'),
p('Small-sample procedures can disagree when a few recoveries drive the mean. The rank-selection sign calculation originally retained exact ties, and its conventional tie-excluding sensitivity differs from both the archived calculation and the paired t-test. Reporting this discrepancy avoids giving an erroneous test label scientific authority. The later internal families retain their corrected null findings. Q15 has its own frozen two-cohort family: its Cho2017 result survives that correction, whereas Lee2019 does not establish either benefit or equivalence. PhysioNet uses a different archived primary test and an amended protocol, so its p-value is not silently absorbed into the newer family.'),
h('4.4. External validation does not resolve every acquisition assumption'),
p('Q15 used a common operational tensor and a committed adapter to make transfer executable across three providers. A common tensor does not establish a common physical measurement. The native export voltage calibration, original Cho acquisition reference, and hardware cue latency were not independently verified. Cho channel order is an explicitly reviewed mapping from the publication montage because the MATLAB payload lacks channel-name strings. Lee event indexing retains a one-native-sample convention discrepancy. These limitations are part of the method’s scope, rather than defects that can be erased by a passing numerical validator.'),
p('The distinction between Q14 and Q15 matters here. The earlier PhysioNet run required a sampling-rate amendment after partial execution, and its later portability validator rechecked existing outputs without replaying inference. Q15 separately froze the preprocessing contract before source fitting and the inference contract before external predictions; its completed scientific validator reports independent raw-to-prediction replay. The manuscript’s own checks only recalculate saved outputs and verify their hash bindings. Keeping these levels separate lets a reader assess reproducibility without mistaking a launcher, a saved status flag, or an API response for scientific validation.'),
p('All models were evaluated offline with zero-phase filtering. No online latency, prospective assistive-control performance, clinical population, or patient benefit was tested. The two-second Q15 crop also excludes part of each imagery interval and does not reproduce each provider’s original benchmark. A useful next experiment would preregister a fully calibrated adapter and compare frozen source-only models on another cohort, with per-class and per-person outcomes specified before access. Such a study would test the boundary revealed here; the present results do not justify retuning on the held-out cohorts and calling the resulting performance external confirmation.'),
h('5. Conclusion', 1),
p('In this experimental audit, source-only training-duration choices produced large but concentrated changes in a small development benchmark. Fixed shared mu/beta representations did not confer a consistent cross-person or external-cohort advantage. The completed Cho2017 evaluation showed a 1.513-pp reduction relative to broad EEGNet; Lee2019 remained compatible with a small effect in either direction. Person-level diagnostics, explicit source and inference freezes, and complete adverse-result reporting provide a firmer account of these decoders than an aggregate improvement claim. Unknown acquisition calibration and offline evaluation limit deployment and physiological conclusions.'),
h('Data, code, ethics, and author declarations', 1),
p('The study uses public BNCI2014_001, PhysioNet, Cho2017, and Lee2019 recordings [1,2,9–15]; the providers’ licenses and usage terms apply. PhysioNet platform sources are cited separately [11,22]. No new participants were recruited and raw EEG is not redistributed in this manuscript bundle. The original collection ethics and participant consent are described in the providers’ publications. The author confirms that neither ethics approval nor an exemption was required for this secondary analysis. No approval or exemption identifier is applicable.'),
p('Code and archived experiments are available at https://github.com/jackzhu119/cross-subject-mi-eeg. This paper uses completed Q15 results verified at commit bc48b257eb44f412ad069f50d0f1a72a33c3c520, with publication readback evidence and final status archived on q15/run-20261005T050511Z-migration-from-r2-b82ad79b. The source scientific revision is 271af288a2f3863430ab80e3145c2dee9bd5571d. The companion evidence files record exact contracts, checkpoints, publication hashes, numerical reanalysis, validation scope, and the reviewed prior manuscript. Repository publication verifies preservation of artifacts, not independent scientific replication or physical server shutdown.'),
p('Author and corresponding author: Ziyuan Zhu. The title-page affiliation follows the author-provided institution and corroborated published English usage. Funding: This research received no funding. Competing interests: The author declares no competing interests. AI assistance was used for manuscript drafting, language revision, analysis-code development, and figure and artifact preparation. The author is responsible for reviewing and approving the final manuscript and for its scientific content. The journal-specific disclosure should describe the actual scope of assistance and follow the selected journal’s policy.'),
]

q15methods = [h('2.7. New binary source freeze and external cohorts (Q15)'),
p('Q15 is a distinct binary transfer experiment, not a continuation of the Q14 checkpoints. All nine BNCI participants supply 2,592 left/right trials. The common ordered montage comprises Fz, FC3, FC1, FC2, FC4, C5, C3, C1, Cz, C2, C4, C6, CP3, CP1, CPz, CP2, CP4, P1, Pz, P2, and POz. Each trial is processed in a fixed native-rate context from −1.5 to +4.5 s relative to the cue. Common-average reference is computed across these 21 selected channels, followed by native-rate zero-phase second-order-section Butterworth filtering with prototype order four. Broad input uses 8–30 Hz; the shared views use 8–13 and 13–30 Hz. Deterministic polyphase resampling yields 160 Hz, followed by the half-open cue crop [0.5,2.5) s, equivalent to samples [320,640) of the resampled six-second context. The model tensor is therefore 21 × 320, and the learned decoder cannot be compared to Q14 as if only the external provider changed.'),
p('The Q15 adapter treats native numeric values under a native-numeric-as-microvolt convention. It does not independently verify physical voltage calibration, the original Cho hardware reference, or hardware cue latency. The first 64 of the Cho payload’s 68 rows are EEG; four EMG rows are excluded. Channel mapping uses the publication’s numbered montage because the payload does not supply names. Cho native labels left = 1 and right = 2 are retained. Lee native labels left = 2 and right = 1 are deterministically mapped to canonical left = 1 and right = 2. Lee MATLAB cue indices are converted using t − 1; the provider’s stored segments align with Python t, leaving a disclosed one-sample (1-ms) indexing discrepancy that was not changed using outcome scores. The supplement records these adapter assumptions and file-level audit coverage.'),
p('Source-only duration selection uses four groups, [1,2], [3,4], [5,6], and [7,8,9], candidate epochs 1–40, equally weighted mean within-fold ranks of cross-entropy, and the earliest minimum. Final durations are 14 broad epochs and 19 shared epochs. The selection seed is 20260923, and final seeds are 20260924–20260926. Training uses the same configured EEGNet family, optimizer, and fixed-band logit averaging described above, with the Q15 channel/time dimensions. A source-fitted CSP4 + LDA comparator uses a fixed 21-to-20 Helmert coordinate transform after common-average reference, followed by source-only fitting. The external neural comparison is between two complete frozen pipelines with different source-selected durations; it does not isolate parameter sharing or band decomposition alone. The completed source work comprises eight inner neural fits, six final neural fits, and one shallow fit: 15 in total. Migration reused those artifacts and added no source or target fit.'),
p('Official raw metadata for 18 BNCI files and all declared Cho/Lee files were audited before the preprocessing contract was committed; the pre-fit publication was recorded at 2026-10-04 01:33:03 UTC. Source completion was recorded at 01:52:42 UTC. The separate inference freeze was committed on 2026-10-05 at 09:31:05 UTC, before external prediction, and fixes channels, timing, label adapters, transformations, checkpoints, seeds, scoring units, and primary statistical procedures. Preprocessing may inspect event metadata to determine eligibility, but no external labels are used for fitting or model selection. BatchNorm remains in evaluation mode; there is no target alignment, normalization fit, adaptation, or post hoc seed selection.'),
p('All 52 Cho and 54 Lee people were processed under the declared adapters. The completed scientific validator separately replays raw-to-epoch and frozen-model prediction calculations, checks canonical events and scoring populations, verifies inference/source artifact bindings, and recalculates aggregate statistics. Its final report passes with the stated calibration limitations. The Q15 migration supervisor’s initial zero new-fit count describes reuse of the source models, not an absence of the 15 original source fits. Intermediate receipts that predate scientific replay are preserved as historical records; final validation and GitHub readback determine completion.'),
]

q15results = [h('3.6. Completed Cho2017 and Lee2019 transfer: lower accuracy on Cho2017 and an uncertain Lee2019 contrast'),
p('The completed Q15 outputs cover 21,320 unique external trials and 149,240 saved model/seed prediction rows, seven per trial. All canonical labels and event identities, person-level confusion matrices, aggregate balanced accuracies, frozen statistical outputs, and declared artifact bindings passed independent checks. Original source fits remained 15, with zero new migration fits and zero target fits. These counts demonstrate adherence to the source-only fitting rule; they are not independent repetitions of the external experiment.'),
p('On Cho2017, equal-person balanced accuracy was 59.82% for broad EEGNet and 58.31% for shared mu/beta EEGNet. The primary shared-minus-broad mean was −1.513 pp (95% person-bootstrap interval [−2.249,−0.804] pp), with two-sided Monte Carlo sign-flip p = 0.000049998 and two-cohort Holm-adjusted p = 0.000099995. The raw p-value is the Monte Carlo procedure’s minimum attainable value, rather than an exact probability below that resolution. Twelve people favored shared, 37 favored broad, and three were tied within a 10^−15 numerical tolerance. This is a corrected adverse result for the declared representation contrast.'),
p('On Lee2019, broad and shared models achieved 65.51% and 65.72% balanced accuracy. The primary difference was +0.204 pp (95% interval [−0.515,+0.969] pp); raw and Holm-adjusted p-values were both 0.60367. Twenty-three people favored shared, 30 favored broad, and one tied. This result provides no evidence of a reliable improvement and is not an equivalence test. The two sessions were combined within each person, so neither the 108 session records nor the repeated model seeds increase the primary sample size beyond 54.'),
table('Table 5. New external binary evaluation under the Q15 freeze.', ['Cohort / model', 'BA (%)', 'Person SD (pp)', 'Left recall (%)', 'Right recall (%)'], [
 ['Cho2017 / Broad EEGNet', '59.82', '8.64', '46.79', '72.86'],
 ['Cho2017 / Shared mu/beta', '58.31', '7.22', '37.52', '79.10'],
 ['Cho2017 / CSP4 + LDA', '51.99', '5.67', '94.10', '9.88'],
 ['Lee2019 / Broad EEGNet', '65.51', '10.97', '75.56', '55.46'],
 ['Lee2019 / Shared mu/beta', '65.72', '10.76', '72.69', '58.75'],
 ['Lee2019 / CSP4 + LDA', '52.77', '5.57', '85.98', '19.56'],
], 'Neural scores and class recalls are averaged over three seeds within person, then equally over people. Person SD describes heterogeneity, not a standard error. Lee uses only offline-training runs, pooled across two sessions. Primary shared-minus-broad contrasts are −1.513 pp [−2.249,−0.804], Holm p = 0.000100 for Cho, and +0.204 pp [−0.515,+0.969], Holm p = 0.604 for Lee. Class recalls and CSP are descriptive; no additional confirmatory tests were added.'),
p('The CSP comparator was near binary chance on both cohorts and strongly favored left-hand labels. On Cho2017, shared input reduced mean left-hand recall from 46.79% to 37.52%, while right-hand recall increased from 72.86% to 79.10%. On Lee2019, the corresponding recalls changed from 75.56% to 72.69% and from 55.46% to 58.75%. These asymmetric changes are retained rather than hidden by balanced accuracy. They were calculated from the frozen outputs as descriptive checks and did not trigger any threshold, label, adapter, or model change.'),
fig('figure4_q15_external_transfer', 'Figure 4', 'Completed Q15 external evaluation. Cohorts are shown separately, with all person/model scores, equal-person means and person standard deviations, and the frozen paired person-bootstrap 95% intervals. Deep-model scores average three seeds within each person; Lee sessions are pooled before person scoring. Holm p-values belong to the predeclared two-cohort shared-minus-broad family. The common 21-channel, two-second pipeline differs from Q14; no pooled cross-cohort test is shown.'),
]

supp = copy.deepcopy(B[83:])
supp[9] = p(B[92]['text'] + ' For completed Q15, the final scientific validator binds 221 artifacts and the verified result publication binds 223 artifacts at its committed snapshot. The manuscript independently verifies these bindings, 52 source-artifact bindings, and 10 frozen checkpoint/transform bindings, with freeze and manifest documents checked separately. A later status update can legitimately have different bytes from the status snapshot bound to the earlier result commit; hashes are checked at the commit to which the receipt refers. An intermediate completion receipt still marked pending does not supersede the final passing validator.')
supp += [h('S7. External adapter, freeze chronology, and cohort-level sensitivity'),
p('The companion supplementary_methods.md records the 21-channel montage, six-second native context, deterministic cue indexing, native-rate filters, two-second crop, Helmert coordinates, provider label remapping, raw audits, source selection groups, 15 original fits, and source/inference freeze chronology. Cho2017 rows are retained as labeled imagery; 49 people contribute 200 trials and S7, S9, S46 contribute 240. Lee2019 contributes offline-training runs only, 100 trials per session. Every primary person remains in the reported population. The calibration limitations accompany all Q15 claims.'),
fig('figureS2_q15_participant_heterogeneity', 'Figure S2', 'Participant-level Q15 transfer heterogeneity. Saved seed-averaged shared-minus-broad effects and within-person three-seed sample standard deviations (106 paired effects and 212 dispersion points; CSP omitted) are displayed separately for 52 Cho and 54 Lee people. Participant order is descriptive and does not define subgroups or target selection. Repeated seeds and the two Lee sessions are not additional inference units.'),
p('Descriptive seed dispersion was larger for shared than broad input: mean within-person seed SD was 6.014 versus 4.550 pp on Cho, and 3.798 versus 2.887 pp on Lee. These values characterize three fixed source-model seeds rather than an estimated population distribution of training randomness. They are not additional confirmatory hypotheses. Full person/seed metrics and class recalls are supplied in q15_external_subjects.csv, q15_seed_metrics.csv, and q15_model_summary.csv.'),
h('S8. Reproducible manuscript materials'),
p('The manuscript bundle contains consistent English Markdown, editable DOCX, a PDF layout export, standalone LaTeX source with embedded numerical figure panels, the Chinese companion, figure sources and PNG/PDF/SVG exports, participant tables, a completed-condition inventory, verified references, independent numerical-audit scripts, and an author submission checklist. The main paper reports the retained scientific results; operational cloud failure logs do not substitute for scientific endpoints. All manuscript preparation fits and checkpoint-inference counts are zero. Author declarations and journal formatting require author confirmation before submission.'),
]

# Reassemble without fragile in-place insertion offsets.
blocks = B[:12] + [physionet_population] + B[12:35] + q15methods + B[35:65] + q15results + discussion + supp
blocks = revise_blocks(blocks)
ref_data = json.loads((OUT / 'references.json').read_text())
refs = ref_data['references'] if isinstance(ref_data, dict) else ref_data

def ref_text(r):
    if r.get('formatted_citation'): return r['formatted_citation'].replace(', ;', ';')
    authors = r.get('authors', [])
    if isinstance(authors, list): authors = '; '.join(str(a) for a in authors)
    venue = r.get('venue', r.get('journal', ''))
    details = str(r.get('volume', ''))
    if r.get('issue'): details += '(' + str(r['issue']) + ')'
    pages = str(r.get('pages_or_article', r.get('pages', '')))
    if pages: details += (', ' if details else '') + pages
    if r.get('version'): details = 'version ' + str(r['version'])
    return f'{authors} ({r["year"]}). {r["title"]}. {venue}' + (', ' + details if details else '') + '. ' + r.get('url', '')

# Conventional reference numbering follows first appearance. Source participant
# groups are spelled out first so their brackets cannot be mistaken for citations.
for block in blocks:
    if block['type'] == 'paragraph':
        block['text'] = block['text'].replace('[1,2], [3,4], [5,6], and [7,8,9]', 'people 1–2, 3–4, 5–6, and 7–9')
pattern = re.compile(r'\[(\d{1,2}(?:\s*[,–-]\s*\d{1,2})*)\]')
first_seen = []
def expand_ids(text):
    ids = []
    for piece in text.split(','):
        ends = re.split('[–-]', piece.strip())
        ids.extend(range(int(ends[0]), int(ends[-1]) + 1))
    return ids
for block in blocks:
    for match in pattern.finditer(block.get('text', '') + block.get('caption', '') + block.get('note', '')):
        for number in expand_ids(match.group(1)):
            assert 1 <= number <= len(refs)
            if number not in first_seen: first_seen.append(number)
assert len(first_seen) == len(refs), 'Every listed reference must be cited.'
mapping = {old_number: new_number for new_number, old_number in enumerate(first_seen, 1)}
for block in blocks:
    for field in ['text', 'caption', 'note']:
        if field in block:
            block[field] = pattern.sub(lambda m: '[' + ','.join(str(mapping[n]) for n in expand_ids(m.group(1))) + ']', block[field])
refs = [refs[n - 1] for n in first_seen]
(OUT / 'evidence/reference_order.json').write_text(json.dumps({'source_to_manuscript': mapping, 'ordered_keys': [r['key'] for r in refs]}, indent=2) + '\n')

aff = json.loads((OUT / 'evidence/affiliation_verification.json').read_text())
content = {'title': TITLE, 'subtitle': SUBTITLE,
           'authors': [{'name': 'Ziyuan Zhu', 'chinese_name': '朱子元', 'corresponding': True,
                        'affiliation': aff['recommended_affiliation_en'], 'email': 'zzy2630816871@gmail.com'}],
           'date': '7 October 2026', 'blocks': blocks, 'references': [ref_text(r) for r in refs],
           'reference_keys': [r['key'] for r in refs], 'new_fits': 0, 'new_checkpoint_inference': 0,
           'status': 'structured_revision_q16_complete_core_author_declarations_confirmed_final_approval_pending'}
(OUT / 'manuscript_content.json').write_text(json.dumps(content, indent=2, ensure_ascii=False) + '\n')
print(json.dumps({'blocks': len(blocks), 'references': len(refs), 'new_fits': 0}))
